[katex]
src.github = "katex/katex"
fetch.url = "https://github.com/KaTeX/KaTeX/releases/download/$ver/katex.tar.gz"

[normalize-css]
src.github_tag = "necolas/normalize.css"
fetch.github = "necolas/normalize.css"