language: generic

before_script:
  - sudo snap install core
  - sudo snap install --edge zola

script:
  - zola build

deploy:
  provider: pages
  local-dir: public
  repo: linyinfeng/linyinfeng.github.io
  target-branch: master
  fqdn: www.linyinfeng.com
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
