language: generic

before_script:
  - sudo apt-get update
  - sudo apt-get install -y jq
  - which jq
  - curl https://api.github.com/repos/getzola/zola/releases/latest |
    jq '.assets[] | select(.name | test("zola.*unknown-linux-gnu.*")) | .browser_download_url' |
    xargs wget
  - tar -xvf zola*unknown-linux-gnu*

script:
  - ./zola build

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

