#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SOURCE=$(realpath "$DIR/../favicon")
TARGET=$(realpath "$DIR/../static/favicon.ico")

cd "$SOURCE"
xelatex favicon.tex

convert "$SOURCE/favicon.pdf" \
        -background transparent \
        -define icon:auto-resize \
        "$TARGET"
identify "$TARGET"
