name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup cachix
        uses: cachix/cachix-action@master
        with:
          name: linyinfeng
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: 'Build'
        run: |
          nix build .#blog
      - name: 'Copy'
        run: |
          cp --recursive --dereference result public
      - name: 'Upload'
        uses: actions/upload-artifact@main
        with:
          name: public
          path: public

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    concurrency: deploy-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Download'
        uses: actions/download-artifact@main
        with:
          name: public
      - name: 'Deploy'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public

  ping-sitemap:
    needs: deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Ping site map'
        run: curl "http://www.google.com/ping?sitemap=https://$(cat static/CNAME)/sitemap.xml"
