name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: linyinfeng
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Build
        run: |
          nix build .#blog
      - name: Check self-contained
        run: |
          [ $(nix path-info --recursive ./result | wc -l) == "1" ]
      - name: Copy and archive
        run: |
          cp --recursive --dereference result public
          tar --verbose --create --use-compress-program=zstd --file public.tar.zst public
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: public.tar.zst

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    concurrency: deploy-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: public
      - name: Unarchive
        run: |
          tar --verbose --extract --file public.tar.zst
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public

  ping-sitemap:
    needs: deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Ping site map'
        run: curl "http://www.google.com/ping?sitemap=https://$(cat static/CNAME)/sitemap.xml"
